acu128504 - [lb_clb] added retry threshold

diff --git a/cookbooks/lb_clb/templates/default/clb_attach_exec.erb b/cookbooks/lb_clb/templates/default/clb_attach_exec.erb
--- a/cookbooks/lb_clb/templates/default/clb_attach_exec.erb
+++ b/cookbooks/lb_clb/templates/default/clb_attach_exec.erb
@@ -92,10 +92,24 @@ attach() {
 
 attach
 
+current_retry=0
+max_retry=32
+
+# If previous attach attempt returns 'PENDING_UPDATE' (meaning the CLB is busy)
+# we will loop for $max_retry times and try to attach again after a random wait time.
 while [[ $status == "PENDING_UPDATE" ]]; do
+
+  if [ $current_retry -gt $max_retry ] ; then
+    echo "Retry limit reached. Failed to attach!"
+    exit 1
+  fi
+
   echo "Load balancer is online but configuration changes are being applied to update the service based on a previous request. Retrying..."
   sleep $(( $RANDOM % 10 ))
   attach
+
+  current_retry=$(( $current_retry + 1 ))
+
 done
 
 exit 0
diff --git a/cookbooks/lb_clb/templates/default/clb_detach_exec.erb b/cookbooks/lb_clb/templates/default/clb_detach_exec.erb
--- a/cookbooks/lb_clb/templates/default/clb_detach_exec.erb
+++ b/cookbooks/lb_clb/templates/default/clb_detach_exec.erb
@@ -94,10 +94,24 @@ detach() {
 
 detach
 
+current_retry=0
+max_retry=32
+
+# If previous detach attempt returns 'PENDING_UPDATE' (meaning the CLB is busy)
+# we will loop for $max_retry times and try to detach again after a random wait time.
 while [[ $status == "PENDING_UPDATE" ]]; do
+
+  if [ $current_retry -gt $max_retry ] ; then
+    echo "Retry limit reached. Failed to detach!"
+    exit 1
+  fi
+
   echo "Load balancer is online but configuration changes are being applied to update the service based on a previous request. Retrying..."
   sleep $(( $RANDOM % 10 ))
   detach
+
+  current_retry=$(( $current_retry + 1 ))
+
 done
 
 exit 0
